# Generated by Django 5.2 on 2025-04-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='電話')),
                ('drink', models.CharField(choices=[('bubble-tea', '珍珠奶茶'), ('mango-green-tea', '芒果綠茶'), ('milk-tea', '鮮奶茶'), ('fruit-tea', '繽紛水果茶'), ('matcha-latte', '抹茶拿鐵'), ('lemon-winter-melon', '檸檬冬瓜茶')], max_length=50, verbose_name='飲品')),
                ('size', models.CharField(choices=[('medium', '中杯'), ('large', '大杯')], max_length=10, verbose_name='杯型')),
                ('toppings', models.CharField(blank=True, max_length=100, verbose_name='配料')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下單時間')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
                'ordering': ['-created_at'],
            },
        ),
    ]
