# Generated by Django 5.2 on 2025-05-06 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待處理'), ('preparing', '製作中'), ('ready', '待取'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='訂單狀態'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
