# Generated by Django 5.2 on 2025-05-20 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink_shop', '0002_order_status_alter_order_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='手機號碼')),
                ('points', models.IntegerField(default=0, verbose_name='積分')),
                ('level', models.CharField(choices=[('bronze', '銅卡會員'), ('silver', '銀卡會員'), ('gold', '金卡會員')], default='bronze', max_length=10, verbose_name='會員等級')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='註冊時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
